;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;; START of the header ;;;;;

.Orig x0500
INIT_CODE
LD R5, STACK_ADDR
ADD R6, R5, #0
LD R4, GLOBAL_DATA_POINTER
LD R7, GLOBAL_MAIN_POINTER
jsrr R7
HALT

LD R7, SERIAL_MONITOR_ADDR
jmp R7
GLOBAL_DATA_POINTER .FILL GLOBAL_DATA_START
GLOBAL_MAIN_POINTER .FILL lc3_main
STACK_ADDR .FILL xdfff
SERIAL_MONITOR_ADDR .FILL x0200

;;;; END of the header ;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;
